[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-macros = { path = "../aoc-macros" }
automod = "1.0.13"
argparse = "0.2.2"
itertools = "0.12.0"
num = "0.4.1"
rayon = "1.8.0"
