[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "aoc-macros"]

[dependencies]
aoc-macros = { path = "aoc-macros" }
argparse = "0.2.2"
automod = "1.0.13"
itertools = "0.12.0"
num = "0.4.1"
rustc-hash = "1.1.0"
